/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package agent.gui;

import agent.InterfaceAgent;
import agent.model.LOEvaluation;
import agent.model.SearchLO;
import agent.model.Student;
import agent.model.StudentList;
import agent.utils.Utils;
import com.google.gson.Gson;
import jade.core.AID;
import jade.lang.acl.ACLMessage;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.IOException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;
import javax.swing.JFileChooser;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author magir
 */
public class GUI extends javax.swing.JFrame {
    
    private InterfaceAgent interfaceAgent;
    private StudentList studentList;
    private File file;
    DefaultListModel modelStudentresult;

    /**
     * Creates new form GUIAgent
     */
    public GUI(InterfaceAgent agent) {
        initComponents();
        
        this.interfaceAgent = agent;
        
        jpSearchLO.setVisible(false);
        jpRecommendationResult.setVisible(false);
        modelStudentresult = new DefaultListModel();
        
        jlStudentResult.setModel(modelStudentresult);
        
        modelStudentresult.addElement("Estudiante-Recomendados-Aceptados");
        
    }
    
    private Student getRowData(String row){
        String[] dataList = row.split(";");
        
        Student student = new Student();
        
        student.setId(dataList[0].trim());
        student.setAge(Integer.valueOf(dataList[1]));
        student.setDisability(dataList[2].trim());
        
        return student;
    }
    
    public void showStudentResult(LOEvaluation lOEvaluation){
        
        modelStudentresult.addElement(lOEvaluation.getStudent().getId() +
                " (" + lOEvaluation.getStudent().getDisability() + ") " + "- " +
                lOEvaluation.getRecommendedLO().getLOList().size() + " - " +
                lOEvaluation.getAcceptedLO().getLOList().size());
        
    }
    
    public void showLOResult(SearchLO searchLO){
        
        jlNumLOResult.setText(String.valueOf(searchLO.getLoList().getLOList().size()));
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpUploadFlatFile = new javax.swing.JPanel();
        jbSelectFile = new javax.swing.JButton();
        jl1 = new javax.swing.JLabel();
        jlFileName = new javax.swing.JLabel();
        jl2 = new javax.swing.JLabel();
        jlNumUsers = new javax.swing.JLabel();
        jbSimulateAgents = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JSeparator();
        jpSearchLO = new javax.swing.JPanel();
        jtfCadenaBusqueda = new javax.swing.JTextField();
        jl3 = new javax.swing.JLabel();
        jbSearchLO = new javax.swing.JButton();
        jl4 = new javax.swing.JLabel();
        jlNumLOResult = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        jpRecommendationResult = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jlStudentResult = new javax.swing.JList<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jpUploadFlatFile.setBackground(new java.awt.Color(0, 153, 153));
        jpUploadFlatFile.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jbSelectFile.setText("Cargar Archivo");
        jbSelectFile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbSelectFileActionPerformed(evt);
            }
        });

        jl1.setText("Archivo:");

        jl2.setText("N° usuarios simulados:");

        jbSimulateAgents.setText("Simular Estudiantes");
        jbSimulateAgents.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbSimulateAgentsActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jpUploadFlatFileLayout = new javax.swing.GroupLayout(jpUploadFlatFile);
        jpUploadFlatFile.setLayout(jpUploadFlatFileLayout);
        jpUploadFlatFileLayout.setHorizontalGroup(
            jpUploadFlatFileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpUploadFlatFileLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpUploadFlatFileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jbSelectFile, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jbSimulateAgents, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jpUploadFlatFileLayout.createSequentialGroup()
                        .addGroup(jpUploadFlatFileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jl1, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jl2, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jpUploadFlatFileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jlFileName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jlNumUsers, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        jpUploadFlatFileLayout.setVerticalGroup(
            jpUploadFlatFileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpUploadFlatFileLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jbSelectFile)
                .addGap(18, 18, 18)
                .addGroup(jpUploadFlatFileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jlFileName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jl1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpUploadFlatFileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jl2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jlNumUsers, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(jbSimulateAgents)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jpSearchLO.setBackground(new java.awt.Color(0, 153, 153));
        jpSearchLO.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jtfCadenaBusqueda.setToolTipText("Cadena de búsqueda");

        jl3.setText("Cadena de búsqueda:");

        jbSearchLO.setText("Buscar OA");
        jbSearchLO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbSearchLOActionPerformed(evt);
            }
        });

        jl4.setText("Resultados:");

        javax.swing.GroupLayout jpSearchLOLayout = new javax.swing.GroupLayout(jpSearchLO);
        jpSearchLO.setLayout(jpSearchLOLayout);
        jpSearchLOLayout.setHorizontalGroup(
            jpSearchLOLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpSearchLOLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpSearchLOLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jbSearchLO, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jpSearchLOLayout.createSequentialGroup()
                        .addComponent(jl3, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jtfCadenaBusqueda))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpSearchLOLayout.createSequentialGroup()
                        .addComponent(jl4, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jlNumLOResult, javax.swing.GroupLayout.PREFERRED_SIZE, 266, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jpSearchLOLayout.setVerticalGroup(
            jpSearchLOLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpSearchLOLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpSearchLOLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtfCadenaBusqueda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jl3))
                .addGap(18, 18, 18)
                .addComponent(jbSearchLO)
                .addGap(18, 18, 18)
                .addGroup(jpSearchLOLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jl4)
                    .addComponent(jlNumLOResult, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jpRecommendationResult.setBackground(new java.awt.Color(0, 153, 153));
        jpRecommendationResult.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jScrollPane1.setViewportView(jlStudentResult);

        javax.swing.GroupLayout jpRecommendationResultLayout = new javax.swing.GroupLayout(jpRecommendationResult);
        jpRecommendationResult.setLayout(jpRecommendationResultLayout);
        jpRecommendationResultLayout.setHorizontalGroup(
            jpRecommendationResultLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpRecommendationResultLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );
        jpRecommendationResultLayout.setVerticalGroup(
            jpRecommendationResultLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpRecommendationResultLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 168, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jpRecommendationResult, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jpUploadFlatFile, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jSeparator2, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jpSearchLO, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jSeparator3, javax.swing.GroupLayout.Alignment.LEADING))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jpUploadFlatFile, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jpSearchLO, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jpRecommendationResult, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbSelectFileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbSelectFileActionPerformed
        FileReader fileReader = null;
        try {
            // TODO add your handling code here:
            JFileChooser fcSeleccionarArchivo = new JFileChooser("C:\\Users\\magir\\Desktop\\Archivos\\Simulación 2017");
            FileNameExtensionFilter filtroExtension = new FileNameExtensionFilter("Filtrar archivos planos", "txt", "csv");
            fcSeleccionarArchivo.setFileFilter(filtroExtension);
            fcSeleccionarArchivo.showOpenDialog(this);
            file = fcSeleccionarArchivo.getSelectedFile();
            
            Integer numRows = 0;
            
            fileReader = new FileReader(file);
            BufferedReader bufferedReader = new BufferedReader(fileReader);
            
            studentList = new StudentList();
            
            String row;
            while ((row = bufferedReader.readLine()) != null) {
                numRows += 1;
                studentList.addStudent(getRowData(row));
            }
            
            System.out.println("Lista de estudiantes cargados");
            System.out.println(studentList);
            
            jlFileName.setText(file.getName());
            if(numRows > 0){
                jlNumUsers.setText(String.valueOf(numRows));
                jpSearchLO.setVisible(true);
            }else{
                jlNumUsers.setText("Debe cargar un archivo con datos");
                jpSearchLO.setVisible(false);
            }
            
        } catch (FileNotFoundException ex) {
            Logger.getLogger(GUI.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(GUI.class.getName()).log(Level.SEVERE, null, ex);
        } finally {
            try {
                fileReader.close();
            } catch (IOException ex) {
                Logger.getLogger(GUI.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        
    }//GEN-LAST:event_jbSelectFileActionPerformed

    private void jbSimulateAgentsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbSimulateAgentsActionPerformed
        
        Gson gson = new Gson();
        String json = gson.toJson(studentList);
        
        Utils utils = new Utils();
        utils.sendMessage(interfaceAgent, 
                new AID("ControllerAgent", AID.ISLOCALNAME), 
                "obj;" + json + ";" + "msg;" + "create simulation agents", 
                ACLMessage.REQUEST);
    }//GEN-LAST:event_jbSimulateAgentsActionPerformed

    private void jbSearchLOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbSearchLOActionPerformed
        Gson gson = new Gson();
        
        SearchLO searchLO = new SearchLO();
        
        searchLO.setSearchString(jtfCadenaBusqueda.getText());
        
        String json = gson.toJson(searchLO);
        
        Utils utils = new Utils();
        utils.sendMessage(interfaceAgent, 
                new AID("ControllerAgent", AID.ISLOCALNAME), 
                "obj;" + json + ";" + "msg;" + "search lo", 
                ACLMessage.REQUEST);
        
        jpRecommendationResult.setVisible(true);
        modelStudentresult.addElement("Cadena de búsqueda: " + jtfCadenaBusqueda.getText());
//        jtfCadenaBusqueda.setText("");
    }//GEN-LAST:event_jbSearchLOActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JButton jbSearchLO;
    private javax.swing.JButton jbSelectFile;
    private javax.swing.JButton jbSimulateAgents;
    private javax.swing.JLabel jl1;
    private javax.swing.JLabel jl2;
    private javax.swing.JLabel jl3;
    private javax.swing.JLabel jl4;
    private javax.swing.JLabel jlFileName;
    private javax.swing.JLabel jlNumLOResult;
    private javax.swing.JLabel jlNumUsers;
    private javax.swing.JList<String> jlStudentResult;
    private javax.swing.JPanel jpRecommendationResult;
    private javax.swing.JPanel jpSearchLO;
    private javax.swing.JPanel jpUploadFlatFile;
    private javax.swing.JTextField jtfCadenaBusqueda;
    // End of variables declaration//GEN-END:variables
}
